algoritmo "Poupança"
// Função :
// Autor :
// Data : 24/03/2019
// Seção de Declarações 
var
Mes1,Mes2,Mes3:real
inicio
// Seção de Comandos 
escreval("Cauculo de um valor de R$500,00 aplicados num período de 3 meses")
escreval("com renda de juros de 1% ao mês")
Mes1<-(500*(1/100))+500
Mes2<-(Mes1*(1/100))+Mes1
Mes3<-(Mes2*(1/100))+Mes2
escreva("O saldo final da poupança, depois dos juros no período, é igual a : ",Mes3)




fimalgoritmo


