algoritmo "Cauculo de tempo"
// Função :
// Autor :
// Data : 24/03/2019
// Seção de Declarações 
var
Seg,Horas,Min:real
inicio
// Seção de Comandos
escreval("Cauculo de horas e minutos tendo como atribuição os segundos")
escreval("Digite a quantidade de segundos")
leia(Seg)
Min<-Seg/60
Horas<-Seg/3600
escreval("O tempo em minutos é: ",Min)
escreva("O tempo em horas é: ", Horas)







 
fimalgoritmo
