algoritmo "Centímetros"
// Função :
// Autor :
// Data : 24/03/2019
// Seção de Declarações 
var
Cent,Met,Dec,Mil:real
inicio
// Seção de Comandos 
escreval("Cauculo de metros, decímetros e milímetros por meio dos centimetros informados")
escreval("Digite a quantidade de centímetros")
leia(Cent)
Met<-Cent/100
Dec<-Cent/10
Mil<-Cent*10
escreval("O valor de metros é: ",Met)
escreval("O valor de decímetros é: ",Dec)
escreval("O valor de milímetros é: ",Mil)


fimalgoritmo
